// <auto-generated />
using System;
using Master_Detail.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Master_Detail.Migrations
{
    [DbContext(typeof(MasterdetaildbContext))]
    [Migration("20250225060813_ono")]
    partial class ono
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Master_Detail.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("OrderId")
                        .HasName("PK__Orders__C3905BAF557FAB32");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Master_Detail.Models.Orderdetail", b =>
                {
                    b.Property<int>("Orderdetailid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("orderdetailid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Orderdetailid"));

                    b.Property<int?>("Amount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasColumnName("amount")
                        .HasComputedColumnSql("([Quantity]*[UnitPrice])", false);

                    b.Property<int?>("Orderid")
                        .HasColumnType("int")
                        .HasColumnName("orderid");

                    b.Property<string>("ProductName")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("UnitPrice")
                        .HasColumnType("int");

                    b.HasKey("Orderdetailid")
                        .HasName("PK__orderdet__7F6004ADF90A6930");

                    b.HasIndex("Orderid");

                    b.ToTable("orderdetail", (string)null);
                });

            modelBuilder.Entity("Master_Detail.Models.Ordertable", b =>
                {
                    b.Property<int>("Orderid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("orderid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Orderid"));

                    b.Property<string>("Username")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("username");

                    b.HasKey("Orderid")
                        .HasName("PK__ordertab__080E377545643B18");

                    b.ToTable("ordertable", (string)null);
                });

            modelBuilder.Entity("Master_Detail.Models.Orderdetail", b =>
                {
                    b.HasOne("Master_Detail.Models.Ordertable", "Order")
                        .WithMany("Orderdetails")
                        .HasForeignKey("Orderid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__orderdeta__order__4BAC3F29");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Master_Detail.Models.Ordertable", b =>
                {
                    b.Navigation("Orderdetails");
                });
#pragma warning restore 612, 618
        }
    }
}
